version: "3"

services:
  personal-data-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: personal-data-app
    ports:
      - '8000:8000'
    external_links:
      - mongo
    environment:
      - NODE_ENV=dev
      - MONGO_URL=mongodb://mongo:27017/personal_data_db
      - SECRET_KEY=xxx
      - JWT_SECRET_OR_KEY=xxx
      - JWT_TOKEN_EXPIRATION=3600000

  mongo:
    container_name: mongo
    image: mongo:4.4.1
    ports:
      - '27017:27017'
